version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.207.0
    ports:
      - "9076:9076"
      - "9090:9090"
    command: -S DocumentDirectory=/apps -S AcceptEULA=${ACCEPT_EULA}
    volumes:
      - ./apps:/apps