version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: qlikcore/engine:12.754.0
        command: -S AcceptEULA=yes
    working_directory: ~/core-qix-session-workout
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run test
          command: |
            DocID=$(curl -s --data-binary @apps/drugcases.qvf http://localhost:9076/v1/apps/import | jq -r '.attributes.id')
            node main.js -c configs/direct-local.json -s scenarios/random-selection-scenario.js -d $DocID --sessionLength 5000 --exit
